---
- hosts: localhost
  gather_facts: no
  #vars_files:
  #  - roles/lee-tower/group_vars/vault.yaml
  #become: yes
  #become_user: root
  
  tasks:

  - name: create the sales demo admin project
    tower_project:
      tower_config_file: ~/tower_cli.cfg
      name: "{{ project_name }}"
      description: "{{ project_description }}"
      organization: Default
      scm_type: git
      scm_url: "https://github.com/{{ scm_username }}/{{ scm_name }}" 
      scm_branch: master
      scm_clean: yes
      scm_delete_on_update: no
      scm_update_on_launch: yes
      state: present


  - name: Ensure all admins have access to the created project
    shell: >
      tower-cli role grant
      --project "{{ project_name }}"
      --team "Operations"
      --type admin
      
  #- name: ensure all admins have use and admin access to the admin project
  #  tower_role:
  #    tower_config_file: ~/tower_cli.cfg
  #    team: Operations
  #    role: "{{ item }}"
  #    project: "{{ project_name }}"
  #    state: present
  #    #tower_verify_ssl: no
  #  with_items:
  #    - use
  #    - admin
    
