---

- name: create all sales demo teams
  tower_team:
    #tower_config_file: ~/tower_cli.cfg
    name: "{{ item.name }}"
    #description: "{{ item.description | default('') }}"
    organization: Default
    state: present
  with_items: "{{ sales_demo_teams }}"
